# Configuration for automatic PR labeling based on file changes
# https://github.com/actions/labeler

# Core areas
"area: cli":
  - changed-files:
    - any-glob-to-any-file: 
      - 'Sources/CLI/**/*'
      - 'Sources/ContainerCommands/**/*'

"area: build":
  - changed-files:
    - any-glob-to-any-file:
      - 'Sources/ContainerBuild/**/*'
      - 'Makefile'
      - 'Package.swift'
      - 'Package.resolved'
      - 'Protobuf.Makefile'

"area: client":
  - changed-files:
    - any-glob-to-any-file: 'Sources/ContainerClient/**/*'

"area: networking":
  - changed-files:
    - any-glob-to-any-file:
      - 'Sources/ContainerNetworkService/**/*'
      - 'Sources/DNSServer/**/*'
      - 'Sources/SocketForwarder/**/*'
      - 'config/container-network-vmnet-config.json'

"area: services":
  - changed-files:
    - any-glob-to-any-file:
      - 'Sources/Services/**/*'
      - 'Sources/ContainerAPIService/**/*'
      - 'Sources/ContainerImagesService/**/*'
      - 'Sources/ContainerSandboxService/**/*'

"area: runtime":
  - changed-files:
    - any-glob-to-any-file:
      - 'Sources/Helpers/RuntimeLinux/**/*'
      - 'config/container-runtime-linux-config.json'

"area: plugin":
  - changed-files:
    - any-glob-to-any-file: 'Sources/ContainerPlugin/**/*'

"area: xpc":
  - changed-files:
    - any-glob-to-any-file: 'Sources/ContainerXPC/**/*'

"area: logging":
  - changed-files:
    - any-glob-to-any-file: 'Sources/ContainerLog/**/*'

"area: persistence":
  - changed-files:
    - any-glob-to-any-file: 'Sources/ContainerPersistence/**/*'

"area: terminal":
  - changed-files:
    - any-glob-to-any-file: 'Sources/TerminalProgress/**/*'

"area: helpers":
  - changed-files:
    - any-glob-to-any-file: 'Sources/Helpers/**/*'

# Testing
"testing":
  - changed-files:
    - any-glob-to-any-file:
      - 'Tests/**/*'
      - '**/*Test*.swift'
      - '**/*Tests.swift'

# Documentation
"documentation":
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '**/*.md'
      - 'scripts/make-docs.sh'

# Configuration
"configuration":
  - changed-files:
    - any-glob-to-any-file:
      - 'config/**/*'
      - '**/*.json'
      - '**/*.toml'
      - 'signing/**/*'

# Scripts and tooling
"tooling":
  - changed-files:
    - any-glob-to-any-file:
      - 'scripts/**/*'
      - 'licenserc.toml'
      - 'Makefile'
      - 'Protobuf.Makefile'

# GitHub specific
"github":
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

# Dependencies
"dependencies":
  - changed-files:
    - any-glob-to-any-file:
      - 'Package.swift'
      - 'Package.resolved'

# C/C++ code
"c/c++":
  - changed-files:
    - any-glob-to-any-file:
      - 'Sources/CVersion/**/*'
      - '**/*.c'
      - '**/*.h'

# Swift protocol buffers
"protobuf":
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.proto'
      - '**/*.pb.swift'
      - '**/*.grpc.swift'
      - 'Protobuf.Makefile'

