# Configuration for automatic PR labeling based on file changes
# https://github.com/actions/labeler

# CLI - Command Line Interface
"area: cli":
  - changed-files:
    - any-glob-to-any-file: 
      - 'Sources/CLI/**/*'
      - 'Sources/ContainerCommands/**/*'

