//===----------------------------------------------------------------------===//
// Copyright © 2026 Apple Inc. and the container project authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

/// The server-owned identity returned by an atomic container create operation.
public struct ContainerCreateResult: Codable, Equatable, Sendable {
    /// The reusable container identifier selected by the caller.
    public let id: String

    /// The opaque identity generated by the API server for this incarnation.
    public let instanceToken: String

    public init(id: String, instanceToken: String) {
        self.id = id
        self.instanceToken = instanceToken
    }
}
