name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label Pull Request
    if: github.repository == 'apple/container'
    runs-on: ubuntu-latest
    outputs:
      labels-applied: ${{ steps.labeler.outputs.labels-applied }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply labels based on file changes
        id: labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true


