name: container project - merge build

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:
    name: Invoke build
    uses: ./.github/workflows/common.yml
    with:
      release: true
    secrets: inherit
    permissions:
      contents: read
      packages: read
      pages: write
